services:
  backend:
    build: .
    restart: always
    platform: linux/x86_64
    volumes:
      - '.:/app'
      - '/app/tmp/pids/'
      - './node_modules:/app/node_modules'
    ports:
      - '3037:3000'  # Rails server
      - '3036:3036'  # Vite dev server
    command: '/app/web_entry.sh'
    stdin_open: true
    depends_on:
      - database
  database:
    image: postgres:18.1-trixie
    restart: always
    platform: linux/x86_64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      PGDATA: '/var/lib/postgresql/data'
    volumes:
      - 'database-data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
volumes:
  database-data:
